jenkinsci/nodelabelparameter-plugin

src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/LabelParameterValue.java

This allows the label value to be exposed in REST API calls with the key 'value'.

[FIXED JENKINS-27880] Expose value field for NodeLabelParameters

---

src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/NodeParameterDefinition.java

When passing the Node definition from a parent job to a child job, the child job cannot be rebuilt using the Rebuild-Plugin as the field with the value in is name 'label' rather than the expected 'labels'. 
Addition of extra case to try to use 'label' if neither 'value' or 'labels' can be found.

[JENKINS-28374] Update NodeParameterDefinition.java to handle rebuilds via Rebuild-Plugin

---

src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/LabelParameterValue.java

ParameterValue.buildEnvVars() is deprecated.  This fix is needed
for the workflow plugin.

[JENKINS-32209] Override ParameterValue.buildEnvironment()

---

src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/LabelParameterDefinition.java

Solved the issue: When triggered by timer, Job with "NodeLabel Parameter Plugin" does not build in parallel on all nodes which share a label. Was using a wrong constructor when getDefaultValue was called.
@imod please, it'd be great if you can review the change. Thanks.
@reviewbybees

[JENKINS-32939] changed the constructor when asking for default value.

---

src/main/resources/org/jvnet/jenkins/plugins/nodelabelparameter/LabelParameterDefinition/index.jelly
src/main/resources/org/jvnet/jenkins/plugins/nodelabelparameter/NodeParameterDefinition/index.jelly
src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/TriggerJobsTest.java

Hi, 
In order to support using NodeLabel parameters in Active Choices plug-in, we can either try to add special logic to support NodeLabel parameters, or try to make the plug-in behave similar to other parameters.
A choice parameter in Jenkins creates the following HTML.
```
<div name="parameter">
<input name="name" value="CCC" type="hidden">
<select name="value"><option value="1">1</option><option value="2">2</option><option value="3">3</option><option value="4">4</option></select></div>
```
But the NodeLabel parameter creates the following HTML.
```
<div description="" name="parameter">
<input name="name" value="NODES_PARAM" type="hidden">
<select name="labels"><option value="master">master</option><option value="manga">manga</option><option value="test1">test1</option></select></div> …
```

Use value as the parameter element, instead of labels

---

src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/wrapper/TriggerNextBuildWrapper.java

On the master node, getBuiltOnStr() returns the empty string. triggerAllBuildsConcurrent does not trigger any concurrent builds if initalBuildNode is "blank", which includes being the empty string.
https://issues.jenkins-ci.org/browse/JENKINS-33746

[JENKINS-33746] Start parallel jobs even if running on master

---

pom.xml

GitHub is deprecating git:// protocol

Use https:// instead of git:// as pom scm URL

---

pom.xml

Plugin pom 4.27 inadvertently disabled coverage reporting.

Fix coverage reporting with pom 4.28

---

Jenkinsfile
README.md
pom.xml
src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/LabelParameterDefinition.java
src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/LabelParameterValue.java
src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/NodeParameterDefinition.java
src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/NodeUtil.java
src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/node/NodeEligibility.java
src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/AllNodesBuildParameterFactory.java
src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/AllNodesForLabelBuildParameterFactory.java
src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/NodeListBuildParameterFactory.java
src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/NodelLabelNodePropertyTest.java
src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/TriggerJobsTest.java
src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/AllNodesForLabelBuildParameterFactoryTest.java

Fresh installations of Jenkins 2.309 and later use the label 'built-in' for the node that is available from the controller.  Adapt the plugin and its tests to work with both the original naming of the controller node and the more inclusive new naming of the controller node.
* Allow parallel tests
* Fix assertion spelling error, reduce runtime
* [JENKINS-66511] Adapt test for inclusive naming
* [JENKINS-66511] Inclusive naming fix for TriggerJobsTest
* [JENKINS-66511] Adapt parameter definition for inclusive naming
* [JENKINS-66511] Use controller label instead of 'master'

[JENKINS-66511] Support inclusive naming

---

src/main/webapp/lib/nodelabel.js

The ATH is failing (relatively reliably in CI, but not locally) presumably due to a timing issue.
Failure is due to:
```
JavaScript error:
http://127.0.0.1:65293/static/659022bd/plugin/nodelabelparameter/lib/nodelabel.js,
line 48: TypeError: document.querySelector(...) is null
```
https://github.com/jenkinsci/nodelabelparameter-plugin/blob/5c9da6313133f254b9ce3eb60712afd3294bd6ca/src/main/webapp/lib/nodelabel.js#L48
it may be that the page is being unloaded immediately after being loaded, or that the ready condition is not correct.
This change is more defensive and checks the element is not null before checking a property of it.
I've checked interactively with the Chrome debugger and I'm able to reach the modified line that shows the change.  The new check for null does not seem to harm …

[JENKINS-66891] Check querySelector is not null before reading value

---

pom.xml

Better to prevent them in the future than rely on code review to detect them.

Prevent unused Java imports

---

pom.xml

It's not good to declare an explicit dependency on a library provided by core. Better just to get it from the core baseline. `plugin-util-api` fails to do this, causing problems for downstream consumers like this plugin. Work around that by excluding the problematic trail via its top-level direct dependency (`parameterized-trigger`). As a bonus I also removed the unused `jenkins-test-harness-tools`.

POM fixups

---

src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/NodeParameterDefinition.java

See https://github.com/jenkinsci/nodelabelparameter-plugin/pull/68#issuecomment-1000799754
Caused by https://github.com/jenkinsci/nodelabelparameter-plugin/commit/82e092e2ef93ef2e76523eb567ac33d4b09a9c1d
Follow up commits reverted the field rename but not the parameter

Fix saving from UI

---

pom.xml
src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/LabelParameterDefinition.java
src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/LabelParameterValue.java
src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/MultipleNodeDescribingParameterDefinition.java
src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/NodeListBuildParameterFactory.java
src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/wrapper/TriggerNextBuildWrapper.java

I doubt this workaround is still needed. I guess we'll find out if the CI build passes.

Remove unnecessary workaround

---

Jenkinsfile

Eventually we'll be dropping support for Java 8.  Compile and test with Java 11 and Java 8.

Run JDK 11 and 8 in ci

---

Jenkinsfile
src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/AllNodesForLabelBuildParameterFactory.java

Combines #107, #108, and #110, then adds Java 17.
- Use parent pom 4.39
- Require Jenkins 2.319.3 or newer
- Bump spotless-maven-plugin from 2.21.0 to 2.22.0
- Use latest 2.319.x bom
- Use parent pom 4.40
- Remove java.level property
- Replace wiki references with plugins.jenkins.io
- Null pointer guard getLabel()
- Test with Java 17 in addition to Java 11 and Java 8

Test Java 17 in addition to Java 11 and Java 8

---

src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/AllNodesBuildParameterFactory.java

Builds are triggered on agents.

javadoc: Builds are triggered on agents

---

src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/LabelParameterDefinition.java
src/main/resources/org/jvnet/jenkins/plugins/nodelabelparameter/LabelParameterDefinition/index.jelly

Fixed missing change: `label` -> `value`
Resolves issue [JENKINS-66175](https://issues.jenkins.io/browse/JENKINS-66175) and [JENKINS-68620](https://issues.jenkins.io/browse/JENKINS-68620)
The previous commit that broke the feature: https://github.com/jenkinsci/nodelabelparameter-plugin/commit/a9c89e637f2d5d9f5dc0ebbceae3fc7a1ae4e08a
- ~~Ensure you have provided tests - that demonstrates feature works or fixes the issue~~
No test, but did mvn install and tested the hpi file

[JENKINS-66175 - Show nodes when the button is clicked

---

CONTRIBUTING.md

Discovered while exploring test creation with Gitpod.

Coverage reporting works best with a clean build

---

CONTRIBUTING.md

Adding instructions to understand test coverage in `CONTRIBUTING.md`
As a newbie, I was confused to get to the bottom of it. Here I am documenting the steps that helped me.

feat: adding intructions to understand test coverage in contributing.md

---

Jenkinsfile
pom.xml

87% of installations of the most recent release are running Jenkins 2.346.1 or newer. Not leaving many behind by requiring at least Jenkins 2.346.3

Require Jenkins 2.346.3 or newer

---

.github/dependabot.yml

Plugin releases are infrequent. No reason to update dependencies more
than once a month.

Check monthly for dependency updates

---

pom.xml

https://github.com/jenkinsci/parameterized-trigger-plugin/releases/tag/parameterized-trigger-2.44 was released in July 2022 and includes the security fixes from the 2.43.1 release.  No significant regressions reported since that release. This removes a GitHub warning and will help users that have not upgraded to have one less security vulnerability.

Bump parameterized trigger plugin to 2.44

---

pom.xml
src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/Constants.java
src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/LabelBadgeAction.java
src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/LabelParameterDefinition.java
src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/LabelParameterValue.java
src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/NextLabelCause.java
src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/NodeParameterDefinition.java
src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/NodeParameterValue.java
src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/node/NodeEligibility.java
src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/AllNodesBuildParameterFactory.java
src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/AllNodesForLabelBuildParameterFactory.java
src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/NodeLabelBuildParameter.java
src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/NodeListBuildParameterFactory.java
src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/wrapper/TriggerNextBuildWrapper.java
src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/NodelLabelNodePropertyTest.java
src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/TriggerJobsTest.java
src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/AllNodesForLabelBuildParameterFactoryTest.java
src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/AllNodesForLabelBuildParameterFactoryUnitTest.java
src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/NodeLabelBuildParameterTest.java
src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/NodeListBuildParameterFactoryTest.java

Google Java Format is an excellent formatter for 2-space, 100 line codebases. Its [Rectangle Rule](https://github.com/google/google-java-format/wiki/The-Rectangle-Rule) has a high degree of conceptual purity, and this works well in the context of 2-space, 100 line codebases where it was designed. If starting from scratch, or if radical changes to existing code style were on the table, this would be my ideal formatter.
For existing 4-space, 120 line codebases where radical changes to existing code style are not on the table, Google Java Format has some critical flaws. Its 4-space "AOSP" mode does not work well at all, and it was not the primary use case. In practice the combination of 4-space mode and the rectangle rule results in unreadable code for lambdas. I have complained about this …

Format code with Palantir Java Format

---

src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/NodeLabelBuildParameterTest.java

part of [JENKINS-69756 mprove node label parameter plugin automated test coverage](https://issues.jenkins.io/browse/JENKINS-69756)

added test to increase test coverage for LabelParameterDefinition

---

Jenkinsfile
pom.xml
src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/AllNodesForLabelBuildParameterFactoryTest.java

- Test Jenkins 2.407 on ci.jenkins.io
- Require Jenkins 2.387.3 or newer
- Use plugin BOM 2133.v2e6c00fe4d61
Verified plugin tests run successfully on Linux Java 11 with Jenkins 2.387.3 as minimum Jenkins version.  Will rely on ci.jenkins.io to verify Windows with Java 17 and Jenkins 2.407.

Require Jenkins 2.387.3 or newer

---

src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/LabelParameterDefinition.java
src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/LabelParameterValue.java

Replaces deprecated usages of `ANTLRException` with the more generic `IllegalArgumentException`, now documented in the core Javadoc.

Remove deprecated usages of `ANTLRException`

---

src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/EnvironmentContributorTest.java

Windows test execution tends to be slower, especially for tests that are based on JenkinsRule.  Allow extra time to complete the tests.
Confirmed tests pass on Linux.  Will use ci.jenkins.io to test the pull request multiple times before it is merged.

Extend Windows timeout for a flaky test

---

src/main/resources/org/jvnet/jenkins/plugins/nodelabelparameter/LabelParameterDefinition/config.jelly
src/main/resources/org/jvnet/jenkins/plugins/nodelabelparameter/NodeParameterDefinition/config.jelly

https://issues.jenkins.io/browse/JENKINS-73974
Going to the configuration page of a freestyle job and adding node and/or label parameters is enough to trigger the violation.
https://www.loom.com/share/1919640546d84ad8a66946cd4f587951
https://www.loom.com/share/7e88064256f44aaab8de09fdb7ea9c51?sid=9c2b9edd-4af1-4254-a133-112df6afaee6

[JENKINS-73974] Remove empty `script` tags for CSP compatibility

---

src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/TriggerJobsTest.java
src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/NodeLabelBuildParameterTest.java

Tested the label parameters within the node label builder. The Assert method was used to evaluate tests. The automated tests within the console were successful.

Improve NodeParameterValue and LabelParameterValue test coverage

---

pom.xml
src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/LabelParameterValueTest.java
src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/NodeParameterValueTest.java
src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/AllNodesForLabelBuildParameterFactoryUnitTest.java
src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/NodeLabelBuildParameterTest.java
src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/NodeListBuildParameterFactoryTest.java

Hello @MarkEWaite, Added some test case which improved the overall test coverage from 76% to 80%.

Improve test coverage of NodeLabelParameter

---

src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/AllNodesBuildParameterFactoryTest.java

I have added automated tests for the AllNodesBuildParameterFactory class

Add test for AllNodesBuildParameterFactory class

---

src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/NextLabelCause.java
src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/NextLabelCauseTest.java

The equals method and the hashCode method both would throw a null pointer exception if the label in the constructor was null.  I doubt that the label in the constructor has ever been null, but it is easy to safeguard those two methods so that they are null-safe.
The code incorrectly tested the equals contract of the wrong class due to my copy and paste error.  Test the correct class.
Uses the simple() verifier because the UpstreamCause class seems to have complications related to its superclass and I'd rather not spend the time to investigate further.  The simple() verifier detected the null pointer exceptions, so it is still better than not testing.
Special thanks to @code-arnab for detecting and reporting the mistake in https://github.com/jenkinsci/nodelabelparameter-plugin/pull/371#issu …

Prevent null pointer exceptions in NextLabelCause

---

src/main/resources/org/jvnet/jenkins/plugins/nodelabelparameter/LabelBadgeAction/badge.jelly
src/main/resources/org/jvnet/jenkins/plugins/nodelabelparameter/NodeParameterDefinition/config.jelly
src/main/resources/org/jvnet/jenkins/plugins/nodelabelparameter/NodeParameterDefinition/index.jelly
src/main/resources/org/jvnet/jenkins/plugins/nodelabelparameter/NodeParameterDefinition/style.css

- use a symbol for the badge
- apply Jenkins style to the select for the node parameter. Suppress the scrollbar when multiple hsot can be selected
Before:
After:
Manual interactive testing

Use symbol for build history badge and consistent styling for parameter lists

---

src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/AllNodesForLabelBuildParameterFactoryUnitTest.java

Part of [JENKINS-69756](https://issues.jenkins.io/browse/JENKINS-69756)
- Implemented a test cases to cover scenarios in getParams method
1. Expect method to catch MacroEvaluationException
2. Expect method to handle online and offline nodes correctly when ignoreOffline == true

[JENKINS-69756] Improve test coverage for AllNodesForLabelBuildParameterFactory

---

src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/AllNodesForLabelBuildParameterFactoryUnitTest.java

This test was added after the transition to Java 17 and likely missed during code review.
Confirmed that tests pass

Use Java 17 pattern matching instanceof in test

---

src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/NodeUtil.java
src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/LabelBadgeActionTest.java
src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/NodeUtilTest.java
src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/node/NodeEligibilityTest.java
src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/wrapper/TriggerNextBuildWrapperTest.java

[JENKINS-69756](https://issues.jenkins.io/browse/JENKINS-69756?jql=labels%20%3D%20newbie-friendly%20and%20status%20in%20(Open%2C%20%22To%20Do%22%2C%20Reopened))

[JENKINS-69756] Improved test coverage.

---

src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/NodeParameterDefinitionTest.java

[JENKINS-69756](https://issues.jenkins.io/browse/JENKINS-69756?jql=labels%20%3D%20newbie-friendly%20and%20status%20in%20(Open%2C%20%22To%20Do%22%2C%20Reopened))

[JENKINS-69756] Improved test coverage of node label parameter plugin
