.gitignore, src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/LabelParameterDefinition.java, src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/LabelParameterValue.java, src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/wrapper/TriggerNextBuildWrapper.java
[JENKINS-22185](https://issues.jenkins-ci.org/browse/JENKINS-22185)
@reviewbybees
=> [JENKINS-22185] Trigger a build in all nodes matching a label

.github/CODEOWNERS, .mvn/extensions.xml, .mvn/maven.config, pom.xml
Updating `pom.xml` to follow the latest recommendations from the archetypes.
=> Incrementalize plugin

src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/LabelParameterDefinition.java, src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/AllNodesBuildParameterFactory.java, src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/AllNodesForLabelBuildParameterFactory.java, src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/NodeListBuildParameterFactory.java, src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/NodelLabelNodePropertyTest.java, src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/TriggerJobsTest.java, src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/AllNodesForLabelBuildParameterFactoryTest.java, src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/AllNodesForLabelBuildParameterFactoryUnitTest.java
See [the mailing list thread](https://groups.google.com/g/jenkinsci-dev/c/aYUJ4VuOuVc).
=> Remove usages of Guava

README.md
=> Minor phrasing improvement

CHANGELOG.md, src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/NodeParameterDefinition.java, src/main/webapp/nodeparam.html
* Use builtin in private method name
* Use agent instead of slave in UI strings
=> More inclusive terminology

src/main/resources/org/jvnet/jenkins/plugins/nodelabelparameter/LabelBadgeAction/badge.jelly
@MarkEWaite Preparation for https://github.com/jenkinsci/jenkins/pull/5778
=> Prepare for PNG icon removal from core

pom.xml, src/main/resources/index.jelly
- Use parent pom 4.39
- Require Jenkins 2.319.3 or newer
=> require 2.319.3

src/main/resources/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/AllNodesForLabelBuildParameterFactory/help-nodeLabel.html, src/main/resources/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/NodeLabelBuildParameter/help-nodeLabel.html, src/main/resources/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/NodeListBuildParameterFactory/help-nodeListString.html, src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/TriggerJobsTest.java
The wiki,jenkins.io site is no longer maintained.
=> Replace wiki references with plugins.jenkins.io

src/main/resources/org/jvnet/jenkins/plugins/nodelabelparameter/NodeParameterDefinition/help-nodeEligibility.html
Found and fixed a spelling mistake in the use of "there" vs "their".
- ~~Ensure you have provided tests - that demonstrates feature works or fixes the issue~~
=> fixed spelling as wrong "their" was used

src/main/resources/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/NodeLabelBuildParameter/help-name.html
- ~~Ensure you have provided tests - that demonstrates feature works or fixes the issue~~
=> Changed "then" to "than"

.gitpod.yml
The DevOps World GitPod session and the Contributing to Open Source session provided this simpler definition.
- ~~Ensure you have provided tests - that demonstrates feature works or fixes the issue~~
=> Simplify Gitpod definition

CONTRIBUTING.md, src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/NodeListBuildParameterFactoryTest.java
Asserted the values passed to the constructors.
=> Test  the `NodeListBuildParameterFactory` constructor

src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/NodeParameterDefinition.java
Spotbugs has improved their detection and no longer complains about these items.
=> Remove spotbugs suppressions that are not needed

CONTRIBUTING.md, pom.xml, src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/Constants.java, src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/LabelBadgeAction.java, src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/LabelParameterDefinition.java, src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/LabelParameterValue.java, src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/MultipleNodeDescribingParameterDefinition.java, src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/NextLabelCause.java, src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/NodeParameterDefinition.java, src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/NodeParameterValue.java, src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/NodeUtil.java, src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/node/AllNodeEligibility.java, src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/node/IgnoreOfflineNodeEligibility.java, src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/node/IgnoreTempOfflineNodeEligibility.java, src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/node/NodeEligibility.java, src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/AllNodesBuildParameterFactory.java, src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/AllNodesForLabelBuildParameterFactory.java, src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/NodeLabelBuildParameter.java, src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/NodeListBuildParameterFactory.java, src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/wrapper/TriggerNextBuildWrapper.java, src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/NodelLabelNodePropertyTest.java, src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/TriggerJobsTest.java, src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/AllNodesForLabelBuildParameterFactoryTest.java, src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/AllNodesForLabelBuildParameterFactoryUnitTest.java, src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/NodeLabelBuildParameterTest.java, src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/NodeListBuildParameterFactoryTest.java
Simplify maintenance by automating code formatting and and pom formatting.
Format with `mvn spotless:apply`.
=> Automate formatting

pom.xml, src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/AllNodesForLabelBuildParameterFactory.java, src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/NodeListBuildParameterFactory.java, src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/wrapper/TriggerNextBuildWrapper.java, src/spotbugs/excludesFilter.xml
Prevent any new spotbugs warnings by specifically excluding known issues.
=> Enable more spotbugs checks

src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/NodelLabelNodePropertyTest.java, src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/TriggerJobsTest.java, src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/NodeListBuildParameterFactoryTest.java
part of [JENKINS-69756 mprove node label parameter plugin automated test coverage](https://issues.jenkins.io/browse/JENKINS-69756)
=> added test to increase test coverage for Node List and Node Lable and tigger job

pom.xml, src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/TriggerJobsTest.java
https://github.com/jenkinsci/plugin-pom/releases/tag/plugin-4.66
Linux compiled and tested with Java 11.
=> Use parent pom 4.66

src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/AllNodesForLabelBuildParameterFactoryUnitTest.java, src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/NodeListBuildParameterFactoryTest.java
While reviewing the @Test annotation, I updated the documentation to be
more accurate and more readable.
Tests pass on Java 11 Linux.
```[tasklist]
```
=> Improve test docs

pom.xml, src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/AllNodesForLabelBuildParameterFactoryUnitTest.java, src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/NodeListBuildParameterFactoryTest.java
- Use hamcrest assertions instead of assertj
- Remove explicit parameterized-trigger version
Automated tests pass on Java 11 with Linux.  Rely on ci.jenkins.io for other tests.
=> Simplify dependencies

pom.xml
Remove when plugin pom provides the most recent version
=> Use spotbugs plugin 4.8.2.0

src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/NextLabelCauseTest.java
Part of [JENKINS-69756](https://issues.jenkins.io/browse/JENKINS-69756)
Added unit tests for `NextLabelCause` class.
Test-coverage before:
Test-coverage after:
=> Improve NextLabelCause Test Coverage

pom.xml, src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/LabelParameterDefinition.java, src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/LabelParameterValue.java, src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/NodeParameterDefinition.java, src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/NodeParameterValue.java, src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/wrapper/TriggerNextBuildWrapper.java, src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/TriggerJobsTest.java
Compile with Java 17 and Jakarta EE 9
Confirmed that automated tests pass.
[Dependent plugins](https://plugins.jenkins.io/nodelabelparameter/dependencies/) have been checked that they are not using the `createValue(StaplerRequest)` method or any other method signature changed in this pull request
=> Require Jenkins 2.479.1 or newer

src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/EnvironmentContributorTest.java, src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/IgnoreTempOfflineNodeEligibilityTest.java, src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/LabelParameterDefinitionTest.java, src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/LabelParameterValueTest.java, src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/NextLabelCauseTest.java, src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/NodeParameterDefinitionTest.java, src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/NodeParameterValueTest.java, src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/NodelLabelNodePropertyTest.java, src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/TriggerJobsTest.java, src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/AllNodesBuildParameterFactoryTest.java, src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/AllNodesForLabelBuildParameterFactoryTest.java, src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/AllNodesForLabelBuildParameterFactoryUnitTest.java, src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/NodeLabelBuildParameterTest.java, src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/NodeListBuildParameterFactoryTest.java
This PR aims to migrate all tests to JUnit5. Changes include:
* Migrate annotations
* Migrate assertions
* Minor cleanup
* Remove public visibility of test classes and methods
=> Migrate tests to JUnit5
